unit ofd_display_list;
{$mode delphiunicode}{$H+}

{ OFD Display List
  Records rendering commands generated by page compiler.
  Display list is independent of specific rendering backend (LCL, Cairo, BGRA).
  Supports: fill path, stroke path, glyph run, image, clip, group, transform.
  Can be serialized to JSON for diagnostics.

  Does not depend on LCL. }

interface

uses
  Classes, SysUtils, Contnrs, Math, ofd_types, ofd_canvas_intf, ofd_glyphrun,
  ofd_ttf_glyf, ofd_render_outcome;

type
  { Forward declaration: a pattern-fill command may carry a nested display
    list (the pattern cell content) that the renderer tiles across the fill
    region. }
  TOFDDisplayList = class;

  { Display list command types }
  TOFDCommandType = (
    ctFillPath, ctStrokePath, ctDrawGlyphRun, ctDrawImage, ctDrawImageRect,
    ctPushClip, ctPopClip, ctBeginGroup, ctEndGroup,
    ctTransform, ctFillColor, ctFillOpacity, ctStrokeColor,
    ctStrokeOpacity, ctLineWidth, ctFillRule, ctLineCap,
    ctLineJoin,     ctLineDash, ctSetBlendMode,
    ctSaveState, ctRestoreState, ctResetTransform,
    ctPatternFill, ctAxialShadingFill, ctRadialShadingFill,
    ctDrawSeal
  );

  { Base command class }
  TOFDCommand = class
  public
    CommandType: TOFDCommandType;
    ObjectID: String;
    ObjectType: String;
    constructor Create(AType: TOFDCommandType); virtual;
  end;

  { Glyph run command }
  TOFDGlyphRunCommand = class(TOFDCommand)
  public
    GlyphRun: TOFDGlyphRun;
    constructor Create;
    destructor Destroy; override;
  end;

  { Path command (fill or stroke) }
  TOFDPathCommand = class(TOFDCommand)
  public
    Path: TOFDPathCommands;
    FillRule: TOFDFillRule;
    Color: TOFDColor;
    Alpha: Double;
    LineWidth: Double;
    constructor Create;
    destructor Destroy; override;
  end;

  { Image command }
  TOFDImageCommand = class(TOFDCommand)
  public
    ImageData: TBytes;
    ImageMatrix: TOFDMatrix;
    Alpha: Double;
    constructor Create;
    destructor Destroy; override;
  end;

  { Image command drawing only a sub-rectangle of the source (for 骑缝章 clips).
    DestMatrix encodes the destination rect (in mm) of the clip region. The clip
    region is given in mm relative to the full image's boundary (BoundaryW/H are
    the full seal size, so the renderer can map clip mm -> source pixels). }
  TOFDImageRectCommand = class(TOFDCommand)
  public
    ImageData: TBytes;
    DestMatrix: TOFDMatrix;
    BoundaryW, BoundaryH: Double; { full image/boundary size in mm }
    ClipLeft, ClipTop, ClipWidth, ClipHeight: Double; { clip region in mm, rel. boundary }
    Alpha: Double;
    constructor Create;
    destructor Destroy; override;
  end;

  { Transform command }
  TOFDTransformCommand = class(TOFDCommand)
  public
    Matrix: TOFDMatrix;
    constructor Create;
  end;

  { Fill color command }
  TOFDFillColorCommand = class(TOFDCommand)
  public
    Color: TOFDColor;
    constructor Create;
  end;

  { Fill opacity command }
  TOFDFillOpacityCommand = class(TOFDCommand)
  public
    Opacity: Double;
    constructor Create;
  end;

  { Clip command }
  TOFDClipCommand = class(TOFDCommand)
  public
    Path: TOFDPathCommands;
    FillRule: TOFDFillRule;
    constructor Create;
    destructor Destroy; override;
  end;

  { Group command }
  TOFDGroupCommand = class(TOFDCommand)
  public
    Alpha: Double;
    BlendMode: TOFDBlendMode;
    Isolated: Boolean;
    IsEnd: Boolean;
    constructor Create(AIsEnd: Boolean);
  end;

  { Line width command }
  TOFDLineWidthCommand = class(TOFDCommand)
  public
    Width: Double;
    constructor Create;
  end;

  { Fill rule command }
  TOFDFillRuleCommand = class(TOFDCommand)
  public
    Rule: TOFDFillRule;
    constructor Create;
  end;

  { Blend mode command }
  TOFDBlendModeCommand = class(TOFDCommand)
  public
    Mode: TOFDBlendMode;
    constructor Create;
  end;

  { Phase 6: Line cap command }
  TOFDLineCapCommand = class(TOFDCommand)
  public
    LineCap: TOFDLineCap;
    constructor Create;
  end;

  { Phase 6: Line join command }
  TOFDLineJoinCommand = class(TOFDCommand)
  public
    LineJoin: TOFDLineJoin;
    constructor Create;
  end;

  { Phase 6: Line dash command }
  TOFDLineDashCommand = class(TOFDCommand)
  public
    Dashes: TDoubleArray;
    Offset: Double;
    constructor Create;
    destructor Destroy; override;
  end;

  { Pattern fill command }
  TOFDPatternFillCommand = class(TOFDCommand)
  public
    Path: TOFDPathCommands;
    Pattern: TOFDPatternSpec;
    Alpha: Double;
    FillRule: TOFDFillRule;
    CellContent: TOFDDisplayList;
    constructor Create;
    destructor Destroy; override;
  end;

  { Nested OFD seal command: the seal is itself a small OFD document (a SES
    electronic-seal container), rendered to an offscreen surface then blitted
    at the destination matrix. }
  TOFDSealCommand = class(TOFDCommand)
  public
    SealData: TBytes;
    DestMatrix: TOFDMatrix;
    constructor Create;
    destructor Destroy; override;
  end;

  { Axial Shading fill command }
  TOFDAxialShadingFillCommand = class(TOFDCommand)
  public
    Path: TOFDPathCommands;
    StartX, StartY: Double;
    EndX, EndY: Double;
    ColorMap: array of TOFDShadingStop;
    Alpha: Double;
    FillRule: TOFDFillRule;
    constructor Create;
    destructor Destroy; override;
  end;

  { Radial Shading fill command }
  TOFDRadialShadingFillCommand = class(TOFDCommand)
  public
    Path: TOFDPathCommands;
    InnerCenterX, InnerCenterY: Double;
    InnerRadius: Double;
    OuterCenterX, OuterCenterY: Double;
    OuterRadius: Double;
    ColorMap: array of TOFDShadingStop;
    Alpha: Double;
    FillRule: TOFDFillRule;
    constructor Create;
    destructor Destroy; override;
  end;

  { Display list - ordered collection of rendering commands }
  TOFDDisplayList = class
  private
    FCommands: TObjectList;
    FFeatures: TOFDRenderFeatureSet;
    function CommandTypeName(Cmd: TOFDCommand): String;
  public
    constructor Create;
    destructor Destroy; override;

    procedure AddCommand(ACommand: TOFDCommand);
    procedure AddGlyphRun(AGlyphRun: TOFDGlyphRun; AColor: TOFDColor; AAlpha: Double);
    procedure AddPath(APath: TOFDPathCommands; AFillRule: TOFDFillRule;
      AColor: TOFDColor; AAlpha: Double);
    procedure AddStrokePath(APath: TOFDPathCommands; AFillRule: TOFDFillRule;
      AColor: TOFDColor; AAlpha: Double; ALineWidth: Double);
    procedure AddImage(AImageData: TBytes; AMatrix: TOFDMatrix; AAlpha: Double);
    procedure AddImageRect(AImageData: TBytes; const ADestMatrix: TOFDMatrix;
      ABoundaryW, ABoundaryH: Double;
      AClipLeft, AClipTop, AClipWidth, AClipHeight: Double; AAlpha: Double);
    procedure AddSeal(const ASealData: TBytes; const ADestMatrix: TOFDMatrix);
    procedure AddTransform(AMatrix: TOFDMatrix);
    procedure AddFillColor(AColor: TOFDColor);
    procedure AddFillOpacity(AOpacity: Double);
    procedure AddStrokeColor(AColor: TOFDColor);
    procedure AddStrokeOpacity(AOpacity: Double);
    procedure AddLineWidth(AWidth: Double);
    procedure AddFillRule(ARule: TOFDFillRule);
    procedure AddBeginGroup(AAlpha: Double; ABlendMode: TOFDBlendMode; AIsolated: Boolean);
    procedure AddEndGroup;
    procedure AddPushClip(APath: TOFDPathCommands; ARule: TOFDFillRule);
    procedure AddPopClip;
    procedure AddLineCap(ACap: TOFDLineCap);
    procedure AddLineJoin(AJoin: TOFDLineJoin);
    procedure AddLineDash(const ADashes: array of Double; AOffset: Double);
    procedure AddSetBlendMode(AMode: TOFDBlendMode);
    procedure AddSaveState;
    procedure AddRestoreState;
    procedure AddResetTransform;
    procedure AddPatternFill(APath: TOFDPathCommands; APattern: TOFDPatternSpec; AAlpha: Double; ARule: TOFDFillRule);
    procedure AddPatternFillWithContent(APath: TOFDPathCommands; APattern: TOFDPatternSpec; ACellContent: TOFDDisplayList; AAlpha: Double; ARule: TOFDFillRule);
    procedure AddAxialShadingFill(APath: TOFDPathCommands; AStartX, AStartY, AEndX, AEndY: Double; const AColorMap: array of TOFDShadingStop; AAlpha: Double; ARule: TOFDFillRule);
    procedure AddRadialShadingFill(APath: TOFDPathCommands; AInnerCX, AInnerCY, AInnerR, AOuterCX, AOuterCY, AOuterR: Double; const AColorMap: array of TOFDShadingStop; AAlpha: Double; ARule: TOFDFillRule);

    function GetCommandCount: Integer;
    property CommandCount: Integer read GetCommandCount;
    function GetCommand(Index: Integer): TOFDCommand;
    procedure Clear;
    function ToJSON: String;
    procedure RecordFeature(AF: TOFDRenderFeature);
    property Features: TOFDRenderFeatureSet read FFeatures;
  end;

implementation

{ TOFDCommand }

constructor TOFDCommand.Create(AType: TOFDCommandType);
begin
  inherited Create;
  CommandType := AType;
  ObjectID := '';
  ObjectType := '';
end;

{ TOFDGlyphRunCommand }

constructor TOFDGlyphRunCommand.Create;
begin
  inherited Create(ctDrawGlyphRun);
  GlyphRun := nil;
end;

destructor TOFDGlyphRunCommand.Destroy;
begin
  GlyphRun.Free;
  inherited Destroy;
end;

{ TOFDPathCommand }

constructor TOFDPathCommand.Create;
begin
  inherited Create(ctFillPath);
  SetLength(Path, 0);
  FillRule := frNonZero;
  Color := RGBColor(0, 0, 0);
  Alpha := 1.0;
end;

destructor TOFDPathCommand.Destroy;
begin
  SetLength(Path, 0);
  inherited Destroy;
end;

{ TOFDImageCommand }

constructor TOFDImageCommand.Create;
begin
  inherited Create(ctDrawImage);
  SetLength(ImageData, 0);
  FillChar(ImageMatrix, SizeOf(ImageMatrix), 0);
  Alpha := 1.0;
end;

destructor TOFDImageCommand.Destroy;
begin
  SetLength(ImageData, 0);
  inherited Destroy;
end;

constructor TOFDImageRectCommand.Create;
begin
  inherited Create(ctDrawImageRect);
  SetLength(ImageData, 0);
  FillChar(DestMatrix, SizeOf(DestMatrix), 0);
  BoundaryW := 0; BoundaryH := 0;
  ClipLeft := 0; ClipTop := 0; ClipWidth := 0; ClipHeight := 0;
  Alpha := 1.0;
end;

destructor TOFDImageRectCommand.Destroy;
begin
  SetLength(ImageData, 0);
  inherited Destroy;
end;

{ TOFDTransformCommand }

constructor TOFDTransformCommand.Create;
begin
  inherited Create(ctTransform);
  FillChar(Matrix, SizeOf(Matrix), 0);
end;

{ TOFDFillColorCommand }

constructor TOFDFillColorCommand.Create;
begin
  inherited Create(ctFillColor);
  Color := RGBColor(0, 0, 0);
end;

{ TOFDFillOpacityCommand }

constructor TOFDFillOpacityCommand.Create;
begin
  inherited Create(ctFillOpacity);
end;

{ TOFDClipCommand }

constructor TOFDClipCommand.Create;
begin
  inherited Create(ctPushClip);
  SetLength(Path, 0);
  FillRule := frNonZero;
end;

destructor TOFDClipCommand.Destroy;
begin
  SetLength(Path, 0);
  inherited Destroy;
end;

{ TOFDGroupCommand }

constructor TOFDGroupCommand.Create(AIsEnd: Boolean);
begin
  if AIsEnd then
    inherited Create(ctEndGroup)
  else
    inherited Create(ctBeginGroup);
  Alpha := 1.0;
  BlendMode := bmNormal;
  Isolated := False;
  IsEnd := AIsEnd;
end;

{ TOFDLineWidthCommand }

constructor TOFDLineWidthCommand.Create;
begin
  inherited Create(ctLineWidth);
  Width := 1.0;
end;

{ TOFDFillRuleCommand }

constructor TOFDFillRuleCommand.Create;
begin
  inherited Create(ctFillRule);
  Rule := frNonZero;
end;

{ TOFDBlendModeCommand }

constructor TOFDBlendModeCommand.Create;
begin
  inherited Create(ctSetBlendMode);
  Mode := bmNormal;
end;

{ TOFDLineCapCommand }

constructor TOFDLineCapCommand.Create;
begin
  inherited Create(ctLineCap);
  LineCap := lcSquare;
end;

{ TOFDLineJoinCommand }

constructor TOFDLineJoinCommand.Create;
begin
  inherited Create(ctLineJoin);
  LineJoin := ljMiter;
end;

{ TOFDLineDashCommand }

constructor TOFDLineDashCommand.Create;
begin
  inherited Create(ctLineDash);
  Offset := 0;
end;

destructor TOFDLineDashCommand.Destroy;
begin
  Dashes := nil;
  inherited Destroy;
end;

{ TOFDPatternFillCommand }

constructor TOFDPatternFillCommand.Create;
begin
  inherited Create(ctPatternFill);
  Alpha := 1.0;
  FillRule := frNonZero;
  CellContent := nil;
end;

destructor TOFDPatternFillCommand.Destroy;
begin
  CellContent.Free;
  SetLength(Path, 0);
  inherited Destroy;
end;

{ TOFDSealCommand }

constructor TOFDSealCommand.Create;
begin
  inherited Create(ctDrawSeal);
end;

destructor TOFDSealCommand.Destroy;
begin
  SetLength(SealData, 0);
  inherited Destroy;
end;

{ TOFDAxialShadingFillCommand }

constructor TOFDAxialShadingFillCommand.Create;
begin
  inherited Create(ctAxialShadingFill);
  Alpha := 1.0;
  FillRule := frNonZero;
  FillChar(ColorMap, SizeOf(ColorMap), 0);
  SetLength(ColorMap, 0);
end;

destructor TOFDAxialShadingFillCommand.Destroy;
begin
  SetLength(Path, 0);
  SetLength(ColorMap, 0);
  inherited Destroy;
end;

{ TOFDRadialShadingFillCommand }

constructor TOFDRadialShadingFillCommand.Create;
begin
  inherited Create(ctRadialShadingFill);
  Alpha := 1.0;
  FillRule := frNonZero;
  FillChar(ColorMap, SizeOf(ColorMap), 0);
  SetLength(ColorMap, 0);
end;

destructor TOFDRadialShadingFillCommand.Destroy;
begin
  SetLength(Path, 0);
  SetLength(ColorMap, 0);
  inherited Destroy;
end;

{ TOFDDisplayList }

constructor TOFDDisplayList.Create;
begin
  inherited Create;
  FCommands := TObjectList.Create(True);
end;

destructor TOFDDisplayList.Destroy;
begin
  FCommands.Free;
  inherited Destroy;
end;

function TOFDDisplayList.CommandTypeName(Cmd: TOFDCommand): String;
begin
  case Cmd.CommandType of
    ctFillPath: Result := 'FillPath';
    ctStrokePath: Result := 'StrokePath';
    ctDrawGlyphRun: Result := 'DrawGlyphRun';
    ctDrawImage: Result := 'DrawImage';
    ctPushClip: Result := 'PushClip';
    ctPopClip: Result := 'PopClip';
    ctBeginGroup: Result := 'BeginGroup';
    ctEndGroup: Result := 'EndGroup';
    ctTransform: Result := 'Transform';
    ctFillColor: Result := 'FillColor';
    ctFillOpacity: Result := 'FillOpacity';
    ctStrokeColor: Result := 'StrokeColor';
    ctStrokeOpacity: Result := 'StrokeOpacity';
    ctLineWidth: Result := 'LineWidth';
    ctFillRule: Result := 'FillRule';
    ctLineCap: Result := 'LineCap';
    ctLineJoin: Result := 'LineJoin';
    ctLineDash: Result := 'LineDash';
    ctSetBlendMode: Result := 'SetBlendMode';
  else
    Result := 'Unknown';
  end;
end;

procedure TOFDDisplayList.AddCommand(ACommand: TOFDCommand);
begin
  FCommands.Add(ACommand);
end;

procedure TOFDDisplayList.AddGlyphRun(AGlyphRun: TOFDGlyphRun;
  AColor: TOFDColor; AAlpha: Double);
var
  Cmd: TOFDGlyphRunCommand;
begin
  Cmd := TOFDGlyphRunCommand.Create;
  Cmd.GlyphRun := AGlyphRun;
  Cmd.ObjectID := AGlyphRun.ObjectID;
  Cmd.ObjectType := 'TextObject';
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddPath(APath: TOFDPathCommands;
  AFillRule: TOFDFillRule; AColor: TOFDColor; AAlpha: Double);
var
  Cmd: TOFDPathCommand;
begin
  Cmd := TOFDPathCommand.Create;
  Cmd.CommandType := ctFillPath;
  Cmd.Path := APath;
  Cmd.FillRule := AFillRule;
  Cmd.Color := AColor;
  Cmd.Alpha := AAlpha;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddStrokePath(APath: TOFDPathCommands;
  AFillRule: TOFDFillRule; AColor: TOFDColor; AAlpha: Double;
  ALineWidth: Double);
var
  Cmd: TOFDPathCommand;
begin
  Cmd := TOFDPathCommand.Create;
  Cmd.CommandType := ctStrokePath;
  Cmd.Path := APath;
  Cmd.FillRule := AFillRule;
  Cmd.Color := AColor;
  Cmd.Alpha := AAlpha;
  Cmd.LineWidth := ALineWidth;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddImage(AImageData: TBytes;
  AMatrix: TOFDMatrix; AAlpha: Double);
var
  Cmd: TOFDImageCommand;
begin
  Cmd := TOFDImageCommand.Create;
  Cmd.ImageData := AImageData;
  Cmd.ImageMatrix := AMatrix;
  Cmd.Alpha := AAlpha;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddImageRect(AImageData: TBytes;
  const ADestMatrix: TOFDMatrix; ABoundaryW, ABoundaryH: Double;
  AClipLeft, AClipTop, AClipWidth, AClipHeight: Double; AAlpha: Double);
var
  Cmd: TOFDImageRectCommand;
begin
  Cmd := TOFDImageRectCommand.Create;
  Cmd.ImageData := AImageData;
  Cmd.DestMatrix := ADestMatrix;
  Cmd.BoundaryW := ABoundaryW;
  Cmd.BoundaryH := ABoundaryH;
  Cmd.ClipLeft := AClipLeft;
  Cmd.ClipTop := AClipTop;
  Cmd.ClipWidth := AClipWidth;
  Cmd.ClipHeight := AClipHeight;
  Cmd.Alpha := AAlpha;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddSeal(const ASealData: TBytes; const ADestMatrix: TOFDMatrix);
var
  Cmd: TOFDSealCommand;
begin
  Cmd := TOFDSealCommand.Create;
  Cmd.SealData := ASealData;
  Cmd.DestMatrix := ADestMatrix;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddTransform(AMatrix: TOFDMatrix);
var
  Cmd: TOFDTransformCommand;
begin
  Cmd := TOFDTransformCommand.Create;
  Cmd.Matrix := AMatrix;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddFillColor(AColor: TOFDColor);
var
  Cmd: TOFDFillColorCommand;
begin
  Cmd := TOFDFillColorCommand.Create;
  Cmd.Color := AColor;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddFillOpacity(AOpacity: Double);
var
  Cmd: TOFDFillOpacityCommand;
begin
  Cmd := TOFDFillOpacityCommand.Create;
  Cmd.Opacity := AOpacity;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddStrokeColor(AColor: TOFDColor);
var
  Cmd: TOFDFillColorCommand;
begin
  Cmd := TOFDFillColorCommand.Create;
  Cmd.CommandType := ctStrokeColor;
  Cmd.Color := AColor;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddStrokeOpacity(AOpacity: Double);
var
  Cmd: TOFDFillOpacityCommand;
begin
  Cmd := TOFDFillOpacityCommand.Create;
  Cmd.CommandType := ctStrokeOpacity;
  Cmd.Opacity := AOpacity;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddLineWidth(AWidth: Double);
var
  Cmd: TOFDLineWidthCommand;
begin
  Cmd := TOFDLineWidthCommand.Create;
  Cmd.Width := AWidth;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddFillRule(ARule: TOFDFillRule);
var
  Cmd: TOFDFillRuleCommand;
begin
  Cmd := TOFDFillRuleCommand.Create;
  Cmd.Rule := ARule;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddBeginGroup(AAlpha: Double;
  ABlendMode: TOFDBlendMode; AIsolated: Boolean);
var
  Cmd: TOFDGroupCommand;
begin
  Cmd := TOFDGroupCommand.Create(False);
  Cmd.Alpha := AAlpha;
  Cmd.BlendMode := ABlendMode;
  Cmd.Isolated := AIsolated;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddEndGroup;
var
  Cmd: TOFDGroupCommand;
begin
  Cmd := TOFDGroupCommand.Create(True);
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddPushClip(APath: TOFDPathCommands;
  ARule: TOFDFillRule);
var
  Cmd: TOFDClipCommand;
begin
  Cmd := TOFDClipCommand.Create;
  Cmd.Path := APath;
  Cmd.FillRule := ARule;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddPopClip;
var
  Cmd: TOFDCommand;
begin
  Cmd := TOFDCommand.Create(ctPopClip);
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddLineCap(ACap: TOFDLineCap);
var
  Cmd: TOFDLineCapCommand;
begin
  Cmd := TOFDLineCapCommand.Create;
  Cmd.LineCap := ACap;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddLineJoin(AJoin: TOFDLineJoin);
var
  Cmd: TOFDLineJoinCommand;
begin
  Cmd := TOFDLineJoinCommand.Create;
  Cmd.LineJoin := AJoin;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddLineDash(const ADashes: array of Double;
  AOffset: Double);
var
  Cmd: TOFDLineDashCommand;
  I: Integer;
begin
  Cmd := TOFDLineDashCommand.Create;
  SetLength(Cmd.Dashes, Length(ADashes));
  for I := 0 to Length(ADashes) - 1 do
    Cmd.Dashes[I] := ADashes[I];
  Cmd.Offset := AOffset;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddSetBlendMode(AMode: TOFDBlendMode);
var
  Cmd: TOFDBlendModeCommand;
begin
  Cmd := TOFDBlendModeCommand.Create;
  Cmd.Mode := AMode;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddSaveState;
var
  Cmd: TOFDCommand;
begin
  Cmd := TOFDCommand.Create(ctSaveState);
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddRestoreState;
var
  Cmd: TOFDCommand;
begin
  Cmd := TOFDCommand.Create(ctRestoreState);
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddResetTransform;
var
  Cmd: TOFDCommand;
begin
  { Reset the current transform back to the base mm->pixel scale. This is used
    for document-level content (e.g. signature stamps) that must be positioned
    in page coordinates regardless of any transform left over from page content. }
  Cmd := TOFDCommand.Create(ctResetTransform);
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddPatternFill(APath: TOFDPathCommands; APattern: TOFDPatternSpec; AAlpha: Double; ARule: TOFDFillRule);
var
  Cmd: TOFDPatternFillCommand;
begin
  Cmd := TOFDPatternFillCommand.Create;
  Cmd.Path := APath;
  Cmd.Pattern := APattern;
  Cmd.Alpha := AAlpha;
  Cmd.FillRule := ARule;
  Cmd.CellContent := nil;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddPatternFillWithContent(APath: TOFDPathCommands;
  APattern: TOFDPatternSpec; ACellContent: TOFDDisplayList; AAlpha: Double;
  ARule: TOFDFillRule);
var
  Cmd: TOFDPatternFillCommand;
begin
  Cmd := TOFDPatternFillCommand.Create;
  Cmd.Path := APath;
  Cmd.Pattern := APattern;
  Cmd.Alpha := AAlpha;
  Cmd.FillRule := ARule;
  Cmd.CellContent := ACellContent;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddAxialShadingFill(APath: TOFDPathCommands; AStartX, AStartY, AEndX, AEndY: Double; const AColorMap: array of TOFDShadingStop; AAlpha: Double; ARule: TOFDFillRule);
var
  Cmd: TOFDAxialShadingFillCommand;
  I: Integer;
begin
  Cmd := TOFDAxialShadingFillCommand.Create;
  Cmd.Path := APath;
  Cmd.StartX := AStartX;
  Cmd.StartY := AStartY;
  Cmd.EndX := AEndX;
  Cmd.EndY := AEndY;
  SetLength(Cmd.ColorMap, Length(AColorMap));
  for I := 0 to Length(AColorMap) - 1 do
    Cmd.ColorMap[I] := AColorMap[I];
  Cmd.Alpha := AAlpha;
  Cmd.FillRule := ARule;
  FCommands.Add(Cmd);
end;

procedure TOFDDisplayList.AddRadialShadingFill(APath: TOFDPathCommands; AInnerCX, AInnerCY, AInnerR, AOuterCX, AOuterCY, AOuterR: Double; const AColorMap: array of TOFDShadingStop; AAlpha: Double; ARule: TOFDFillRule);
var
  Cmd: TOFDRadialShadingFillCommand;
  I: Integer;
begin
  Cmd := TOFDRadialShadingFillCommand.Create;
  Cmd.Path := APath;
  Cmd.InnerCenterX := AInnerCX;
  Cmd.InnerCenterY := AInnerCY;
  Cmd.InnerRadius := AInnerR;
  Cmd.OuterCenterX := AOuterCX;
  Cmd.OuterCenterY := AOuterCY;
  Cmd.OuterRadius := AOuterR;
  SetLength(Cmd.ColorMap, Length(AColorMap));
  for I := 0 to Length(AColorMap) - 1 do
    Cmd.ColorMap[I] := AColorMap[I];
  Cmd.Alpha := AAlpha;
  Cmd.FillRule := ARule;
  FCommands.Add(Cmd);
end;

function TOFDDisplayList.GetCommandCount: Integer;
begin
  Result := FCommands.Count;
end;

function TOFDDisplayList.GetCommand(Index: Integer): TOFDCommand;
begin
  if (Index >= 0) and (Index < FCommands.Count) then
    Result := TOFDCommand(FCommands[Index])
  else
    Result := nil;
end;

procedure TOFDDisplayList.Clear;
begin
  FCommands.Clear;
end;

function TOFDDisplayList.ToJSON: String;
var
  I: Integer;
  Cmd: TOFDCommand;
begin
  Result := '{"commands":[';
  for I := 0 to FCommands.Count - 1 do
  begin
    Cmd := TOFDCommand(FCommands[I]);
    if I > 0 then Result := Result + ',';
    Result := Result + '{"type":"' + CommandTypeName(Cmd) + '"';
    if Cmd.ObjectID <> '' then
      Result := Result + ',"object":"' + Cmd.ObjectID + '"';
    if Cmd.ObjectType <> '' then
      Result := Result + ',"otype":"' + Cmd.ObjectType + '"';
    Result := Result + '}';
  end;
  Result := Result + '],"count":' + IntToStr(FCommands.Count) + '}';
end;

procedure TOFDDisplayList.RecordFeature(AF: TOFDRenderFeature);
begin
  Include(FFeatures, AF);
end;

end.
